<?php

$routes = [
    '' => 'store.php',
    'store.php' => 'store.php',
    'product.php' => '/backend/static/page/catalog/product.php',
    'catalog.php' => '/backend/static/page/catalog/catalog.php',
    'news.php' => '/backend/static/page/news/news.php',
    'company.php' => '/backend/static/page/company/company.php',
    'contacts.php' => '/backend/static/page/contacts/contacts.php',
    'order.php' => '/backend/static/page/orders/order.php',
    'article.php' => '/backend/static/page/news/article.php',
    'test.php' => 'test.php',
    'orderSuccess.php' => '/backend/static/page/orders/orderSuccess.php',
    'register' => '/backend/actions/auth/register.php',
    'auth' => '/backend/actions/auth/auth.php',
    'logout' => '/backend/actions/auth/logout.php',
    'forgotPass' => '/backend/actions/auth/forgotPass.php',
    'basket' => '/backend/actions/basket/basket.php',
    'catalog' => '/backend/actions/catalog/catalog.php',
    'order' => '/backend/actions/orders/orderAction.php',
    'orderItems' => '/backend/actions/orders/orderItems.php',
    'getOrder' => '/backend/actions/orders/getOrder.php',
    'updateBasket' => '/backend/actions/basket/updateBasket.php',
    'clearBasket' => '/backend/actions/basket/clearBasket.php',
    'getBasket' => '/backend/actions/basket/getBasket.php',
    'deleteProduct' => '/backend/actions/basket/deleteProduct.php',
    'reviews' => '/backend/actions/review/reviewList.php',
    'makeReview' => '/backend/actions/review/makeReview.php',
];
